/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_OTM1090A_DJ_1080P_VIDEO_H_

#define _PANEL_OTM1090A_DJ_1080P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/

static struct panel_config otm1901a_dj_1080p_video_panel_data = {
  "qcom,mdss_dsi_otm1901a_dj_1080p_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 1, 50000, 0, 0, 0, 0, 0, 0, NULL
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution otm1901a_dj_1080p_video_panel_res = {
  1080, 1920, 52, 60, 4, 0, 12, 14, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info otm1901a_dj_1080p_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/

static char otm1901a_dj_1080p_video_on_cmd0[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd1[]={
	0x04,0x00,0x29,0xC0,
	0xFF,0x19,0x01,0x01};
static char otm1901a_dj_1080p_video_on_cmd2[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd3[]={
	0x03,0x00,0x29,0xC0,
	0xFF,0x19,0x01};
static char otm1901a_dj_1080p_video_on_cmd4[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd5[]={
	0x02,0x00,0x29,0xC0,
	0x1C,0x33};
static char otm1901a_dj_1080p_video_on_cmd6[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xA0};
static char otm1901a_dj_1080p_video_on_cmd7[]={
	0x02,0x00,0x29,0xC0,
	0xC1,0xE8};
static char otm1901a_dj_1080p_video_on_cmd8[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xA7};
static char otm1901a_dj_1080p_video_on_cmd9[]={
	0x02,0x00,0x29,0xC0,
	0xC1,0x00};
static char otm1901a_dj_1080p_video_on_cmd10[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x90};
static char otm1901a_dj_1080p_video_on_cmd11[]={
	0x07,0x00,0x29,0xC0,
	0xC0,0x00,0x2F,0x00,
	0x00,0x00,0x01};
static char otm1901a_dj_1080p_video_on_cmd12[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xC0};
static char otm1901a_dj_1080p_video_on_cmd13[]={
	0x07,0x00,0x29,0xC0,
	0xC0,0x00,0x2F,0x00,
	0x00,0x00,0x01};
static char otm1901a_dj_1080p_video_on_cmd14[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x9A};
static char otm1901a_dj_1080p_video_on_cmd15[]={
	0x02,0x00,0x29,0xC0,
	0xC0,0x1E};
static char otm1901a_dj_1080p_video_on_cmd16[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xAC};
static char otm1901a_dj_1080p_video_on_cmd17[]={
	0x02,0x00,0x29,0xC0,
	0xC0,0x06};
static char otm1901a_dj_1080p_video_on_cmd18[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xDC};
static char otm1901a_dj_1080p_video_on_cmd19[]={
	0x02,0x00,0x29,0xC0,
	0xC0,0x06};
static char otm1901a_dj_1080p_video_on_cmd20[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x81};
static char otm1901a_dj_1080p_video_on_cmd21[]={
	0x02,0x00,0x29,0xC0,
	0xA5,0x04};
static char otm1901a_dj_1080p_video_on_cmd22[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x84};
static char otm1901a_dj_1080p_video_on_cmd23[]={
	0x02,0x00,0x29,0xC0,
	0xC4,0x20};
static char otm1901a_dj_1080p_video_on_cmd24[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xA5};
static char otm1901a_dj_1080p_video_on_cmd25[]={
	0x02,0x00,0x29,0xC0,
	0xB3,0x1d};
static char otm1901a_dj_1080p_video_on_cmd26[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x92};
static char otm1901a_dj_1080p_video_on_cmd27[]={
	0x02,0x00,0x29,0xC0,
	0xE9,0x00};
static char otm1901a_dj_1080p_video_on_cmd28[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x90};
static char otm1901a_dj_1080p_video_on_cmd29[]={
	0x02,0x00,0x29,0xC0,
	0xF3,0x01};
static char otm1901a_dj_1080p_video_on_cmd30[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xB4};
static char otm1901a_dj_1080p_video_on_cmd31[]={
	0x02,0x00,0x29,0xC0,
	0xC0,0xD0};
static char otm1901a_dj_1080p_video_on_cmd32[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x93};
static char otm1901a_dj_1080p_video_on_cmd33[]={
	0x02,0x00,0x29,0xC0,
	0xC5,0x19};
static char otm1901a_dj_1080p_video_on_cmd34[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x95};
static char otm1901a_dj_1080p_video_on_cmd35[]={
	0x02,0x00,0x29,0xC0,
	0xC5,0x2D};
static char otm1901a_dj_1080p_video_on_cmd36[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x97};
static char otm1901a_dj_1080p_video_on_cmd37[]={
	0x02,0x00,0x29,0xC0,
	0xC5,0x14};
static char otm1901a_dj_1080p_video_on_cmd38[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd39[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x99};
static char otm1901a_dj_1080p_video_on_cmd40[]={
	0x02,0x00,0x29,0xC0,
	0xC5,0x29};
static char otm1901a_dj_1080p_video_on_cmd41[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd42[]={
	0x03,0x00,0x29,0xC0,
	0xD8,0x1D,0x1D};
static char otm1901a_dj_1080p_video_on_cmd43[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xB3};
static char otm1901a_dj_1080p_video_on_cmd44[]={
	0x02,0x00,0x29,0xC0,
	0xC0,0xCC};
static char otm1901a_dj_1080p_video_on_cmd45[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xB4};
static char otm1901a_dj_1080p_video_on_cmd46[]={
	0x02,0x00,0x29,0xC0,
	0xC0,0x80};
static char otm1901a_dj_1080p_video_on_cmd47[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xBC};
static char otm1901a_dj_1080p_video_on_cmd48[]={
	0x02,0x00,0x29,0xC0,
	0xC0,0x00};
static char otm1901a_dj_1080p_video_on_cmd49[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xF7};
static char otm1901a_dj_1080p_video_on_cmd50[]={
	0x05,0x00,0x29,0xC0,
	0xC3,0x04,0x18,0x04,
	0x04};
static char otm1901a_dj_1080p_video_on_cmd51[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x81};
static char otm1901a_dj_1080p_video_on_cmd52[]={
	0x02,0x00,0x29,0xC0,
	0xA5,0x07};
static char otm1901a_dj_1080p_video_on_cmd53[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x9D};
static char otm1901a_dj_1080p_video_on_cmd54[]={
	0x02,0x00,0x29,0xC0,
	0xC5,0x77};
static char otm1901a_dj_1080p_video_on_cmd55[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x9B};
static char otm1901a_dj_1080p_video_on_cmd56[]={
	0x03,0x00,0x29,0xC0,
	0xC5,0x55,0x55};
static char otm1901a_dj_1080p_video_on_cmd57[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd58[]={
	0x02,0x00,0x29,0xC0,
	0xC4,0x15};
/*remove VCOM
static char otm1901a_dj_1080p_video_on_cmd59[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd60[]={
	0x02,0x00,0x29,0xC0,
	0xD9,0x00};
static char otm1901a_dj_1080p_video_on_cmd61[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x01};
static char otm1901a_dj_1080p_video_on_cmd62[]={
	0x02,0x00,0x29,0xC0,
	0xD9,0xB4};
*/
static char otm1901a_dj_1080p_video_on_cmd63[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd64[]={
	0x0f,0x00,0x29,0xC0,
	0xC0,0x00,0x87,0x00,
	0x0A,0x0A,0x00,0x87,
	0x0A,0x0A,0x00,0x87,
	0x00,0x0A,0x0A};
static char otm1901a_dj_1080p_video_on_cmd65[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xF0};
static char otm1901a_dj_1080p_video_on_cmd66[]={
	0x07,0x00,0x29,0xC0,
	0xC3,0x22,0x02,0x00,
	0x00,0x00,0x0C};
static char otm1901a_dj_1080p_video_on_cmd67[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xA0};
static char otm1901a_dj_1080p_video_on_cmd68[]={
	0x08,0x00,0x29,0xC0,
	0xC0,0x00,0x00,0x00,
	0x00,0x03,0x22,0x03};
static char otm1901a_dj_1080p_video_on_cmd69[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xD0};
static char otm1901a_dj_1080p_video_on_cmd70[]={
	0x08,0x00,0x29,0xC0,
	0xC0,0x00,0x00,0x00,
	0x00,0x03,0x22,0x03};
static char otm1901a_dj_1080p_video_on_cmd71[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x90};
static char otm1901a_dj_1080p_video_on_cmd72[]={
	0x09,0x00,0x29,0xC0,
	0xC2,0x83,0x01,0x00,
	0x00,0x82,0x01,0x00,
	0x00};
static char otm1901a_dj_1080p_video_on_cmd73[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd74[]={
	0x0d,0x00,0x29,0xC0,
	0xC3,0x82,0x02,0x03,
	0x00,0x03,0x84,0x81,
	0x03,0x03,0x00,0x03,
	0x84};
static char otm1901a_dj_1080p_video_on_cmd75[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x90};
static char otm1901a_dj_1080p_video_on_cmd76[]={
	0x0d,0x00,0x29,0xC0,
	0xC3,0x00,0x01,0x03,
	0x00,0x03,0x84,0x01,
	0x02,0x03,0x00,0x03,
	0x84};
static char otm1901a_dj_1080p_video_on_cmd77[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd78[]={
	0x10,0x00,0x29,0xC0,
	0xCC,0x09,0x0A,0x11,
	0x12,0x13,0x14,0x15,
	0x16,0x17,0x18,0x28,
	0x28,0x28,0x28,0x28};
static char otm1901a_dj_1080p_video_on_cmd79[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x90};
static char otm1901a_dj_1080p_video_on_cmd80[]={
	0x10,0x00,0x29,0xC0,
	0xCC,0x0A,0x09,0x14,
	0x13,0x12,0x11,0x15,
	0x16,0x17,0x18,0x28,
	0x28,0x28,0x28,0x28};
static char otm1901a_dj_1080p_video_on_cmd81[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xA0};
static char otm1901a_dj_1080p_video_on_cmd82[]={
	0x10,0x00,0x29,0xC0,
	0xCC,0x1D,0x1E,0x1F,
	0x19,0x1A,0x1B,0x1C,
	0x20,0x21,0x22,0x23,
	0x24,0x25,0x26,0x27};
static char otm1901a_dj_1080p_video_on_cmd83[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xB0};
static char otm1901a_dj_1080p_video_on_cmd84[]={
	0x09,0x00,0x29,0xC0,
	0xCC,0x01,0x02,0x03,
	0x05,0x06,0x07,0x04,
	0x08};
static char otm1901a_dj_1080p_video_on_cmd85[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xC0};
static char otm1901a_dj_1080p_video_on_cmd86[]={
	0x0d,0x00,0x29,0xC0,
	0xCC,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x77};
static char otm1901a_dj_1080p_video_on_cmd87[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xD0};
static char otm1901a_dj_1080p_video_on_cmd88[]={
	0x0d,0x00,0x29,0xC0,
	0xCC,0x00,0x00,0x00,
	0x00,0x05,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x77};
static char otm1901a_dj_1080p_video_on_cmd89[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd90[]={
	0x10,0x00,0x29,0xC0,
	0xCB,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd91[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x90};
static char otm1901a_dj_1080p_video_on_cmd92[]={
	0x10,0x00,0x29,0xC0,
	0xCB,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd93[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xA0};
static char otm1901a_dj_1080p_video_on_cmd94[]={
	0x10,0x00,0x29,0xC0,
	0xCB,0x01,0x01,0x01,
	0x01,0x01,0x01,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd95[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xB0};
static char otm1901a_dj_1080p_video_on_cmd96[]={
	0x10,0x00,0x29,0xC0,
	0xCB,0x00,0x01,0xFD,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd97[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xC0};
static char otm1901a_dj_1080p_video_on_cmd98[]={
	0x09,0x00,0x29,0xC0,
	0xCB,0x00,0x00,0x00,
	0x00,0x00,0x00,0x77,
	0x77};
static char otm1901a_dj_1080p_video_on_cmd99[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xD0};
static char otm1901a_dj_1080p_video_on_cmd100[]={
	0x09,0x00,0x29,0xC0,
	0xCB,0x00,0x00,0x00,
	0x00,0x00,0x00,0x77,
	0x77};
static char otm1901a_dj_1080p_video_on_cmd101[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xE0};
static char otm1901a_dj_1080p_video_on_cmd102[]={
	0x09,0x00,0x29,0xC0,
	0xCB,0x00,0x00,0x00,
	0x00,0x00,0x00,0x77,
	0x77};
static char otm1901a_dj_1080p_video_on_cmd103[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xF0};
static char otm1901a_dj_1080p_video_on_cmd104[]={
	0x09,0x00,0x29,0xC0,
	0xCB,0x01,0x01,0x01,
	0x00,0x00,0x00,0x77,
	0x77};
static char otm1901a_dj_1080p_video_on_cmd105[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd106[]={
	0x10,0x00,0x29,0xC0,
	0xCD,0x3F,0x3F,0x3F,
	0x3F,0x3F,0x3F,0x3F,
	0x3F,0x3F,0x02,0x12,
	0x11,0x3F,0x04,0x3F};
static char otm1901a_dj_1080p_video_on_cmd107[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x90};
static char otm1901a_dj_1080p_video_on_cmd108[]={
	0x0c,0x00,0x29,0xC0,
	0xCD,0x06,0x3F,0x3F,
	0x26,0x26,0x26,0x21,
	0x20,0x1F,0x26,0x26};
static char otm1901a_dj_1080p_video_on_cmd109[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xA0};
static char otm1901a_dj_1080p_video_on_cmd110[]={
	0x10,0x00,0x29,0xC0,
	0xCD,0x3F,0x3F,0x3F,
	0x3F,0x3F,0x3F,0x3F,
	0x3F,0x3F,0x01,0x12,
	0x11,0x3F,0x03,0x3F};
static char otm1901a_dj_1080p_video_on_cmd111[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xB0};
static char otm1901a_dj_1080p_video_on_cmd112[]={
	0x0c,0x00,0x29,0xC0,
	0xCD,0x05,0x3F,0x3F,
	0x26,0x26,0x26,0x21,
	0x20,0x1F,0x26,0x26};
static char otm1901a_dj_1080p_video_on_cmd113[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd114[]={
	0x19,0x00,0x29,0xC0,
	0xe1,0x30,0x35,0x36,
	0x3a,0x40,0x44,0x46,
	0x52,0x58,0x66,0x6c,
	0x72,0x88,0x81,0x77,
	0x60,0x4d,0x39,0x2c,
	0x24,0x12,0x09,0x06,
	0x03};
static char otm1901a_dj_1080p_video_on_cmd115[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd116[]={
	0x19,0x00,0x29,0xC0,
	0xe2,0x30,0x35,0x36,
	0x3a,0x40,0x44,0x46,
	0x52,0x58,0x66,0x6c,
	0x72,0x88,0x81,0x77,
	0x60,0x4d,0x39,0x2c,
	0x24,0x12,0x09,0x06,
	0x03};
static char otm1901a_dj_1080p_video_on_cmd117[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd118[]={
	0x19,0x00,0x29,0xC0,
	0xe3,0x1c,0x1d,0x20,
	0x25,0x28,0x2c,0x36,
	0x43,0x48,0x59,0x63,
	0x6c,0x8d,0x84,0x7a,
	0x63,0x4d,0x39,0x2c,
	0x24,0x1d,0x11,0x07,
	0x03};
static char otm1901a_dj_1080p_video_on_cmd119[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd120[]={
	0x19,0x00,0x29,0xC0,
	0xe4,0x1c,0x1d,0x20,
	0x25,0x28,0x2c,0x36,
	0x43,0x48,0x59,0x63,
	0x6c,0x8d,0x84,0x7a,
	0x63,0x4d,0x39,0x2c,
	0x24,0x1d,0x11,0x07,
	0x03};
static char otm1901a_dj_1080p_video_on_cmd121[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd122[]={
	0x19,0x00,0x29,0xC0,
	0xe5,0x00,0x07,0x08,
	0x0d,0x13,0x1b,0x25,
	0x36,0x40,0x52,0x5f,
	0x69,0x8f,0x86,0x7b,
	0x63,0x4d,0x39,0x2c,
	0x24,0x1e,0x0d,0x04,
	0x03};
static char otm1901a_dj_1080p_video_on_cmd123[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd124[]={
	0x19,0x00,0x29,0xC0,
	0xe6,0x00,0x07,0x08,
	0x0d,0x13,0x1b,0x25,
	0x36,0x40,0x52,0x5f,
	0x69,0x8f,0x86,0x7b,
	0x63,0x4c,0x38,0x30,
	0x20,0x1e,0x0d,0x04,
	0x03};
static char otm1901a_dj_1080p_video_on_cmd125[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x81};
static char otm1901a_dj_1080p_video_on_cmd126[]={
	0x02,0x00,0x29,0xC0,
	0xA5,0x07};
static char otm1901a_dj_1080p_video_on_cmd127[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x80};
static char otm1901a_dj_1080p_video_on_cmd128[]={
	0x02,0x00,0x29,0xC0,
	0xC4,0x1A};
static char otm1901a_dj_1080p_video_on_cmd129[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x9B};
static char otm1901a_dj_1080p_video_on_cmd130[]={
	0x03,0x00,0x29,0xC0,
	0xC5,0x55,0x50};
static char otm1901a_dj_1080p_video_on_cmd131[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xF7};
static char otm1901a_dj_1080p_video_on_cmd132[]={
	0x05,0x00,0x29,0xC0,
	0xC3,0x04,0x16,0x04,
	0x04};
static char otm1901a_dj_1080p_video_on_cmd133[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xF2};
static char otm1901a_dj_1080p_video_on_cmd134[]={
	0x04,0x00,0x29,0xC0,
	0xC1,0x80,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd135[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x9D};
static char otm1901a_dj_1080p_video_on_cmd136[]={
	0x02,0x00,0x29,0xC0,
	0xC5,0x77};
static char otm1901a_dj_1080p_video_on_cmd137[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xF7};
static char otm1901a_dj_1080p_video_on_cmd138[]={
	0x05,0x00,0x29,0xC0,
	0xC3,0x00,0xFF,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd139[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xF2};
static char otm1901a_dj_1080p_video_on_cmd140[]={
	0x04,0x00,0x29,0xC0,
	0xC1,0x00,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd141[]={
	0x02,0x00,0x29,0xC0,
	0x00,0xD0};
static char otm1901a_dj_1080p_video_on_cmd142[]={
	0x05,0x00,0x29,0xC0,
	0xF5,0x00,0x00,0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd143[]={
	0x02,0x00,0x29,0xC0,
	0x00,0x00};
static char otm1901a_dj_1080p_video_on_cmd144[]={
	0x04,0x00,0x29,0xC0,
	0xFF,0xFF,0xFF,0xFF};
static char otm1901a_dj_1080p_video_on_cmd145[]={
	0x02,0x00,0x29,0xC0,
	0x51,0xff};
static char otm1901a_dj_1080p_video_on_cmd146[]={
	0x02,0x00,0x29,0xC0,
	0x53,0x24};
static char otm1901a_dj_1080p_video_on_cmd147[]={
	0x11,0x00,0x05,0x80};
static char otm1901a_dj_1080p_video_on_cmd148[]={
	0x29,0x00,0x05,0x80};

static struct mipi_dsi_cmd otm1901a_dj_1080p_video_on_command[] = {
	{sizeof(otm1901a_dj_1080p_video_on_cmd0), otm1901a_dj_1080p_video_on_cmd0, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd1), otm1901a_dj_1080p_video_on_cmd1, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd2), otm1901a_dj_1080p_video_on_cmd2, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd3), otm1901a_dj_1080p_video_on_cmd3, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd4), otm1901a_dj_1080p_video_on_cmd4, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd5), otm1901a_dj_1080p_video_on_cmd5, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd6), otm1901a_dj_1080p_video_on_cmd6, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd7), otm1901a_dj_1080p_video_on_cmd7, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd8), otm1901a_dj_1080p_video_on_cmd8, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd9), otm1901a_dj_1080p_video_on_cmd9, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd10), otm1901a_dj_1080p_video_on_cmd10, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd11), otm1901a_dj_1080p_video_on_cmd11, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd12), otm1901a_dj_1080p_video_on_cmd12, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd13), otm1901a_dj_1080p_video_on_cmd13, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd14), otm1901a_dj_1080p_video_on_cmd14, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd15), otm1901a_dj_1080p_video_on_cmd15, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd16), otm1901a_dj_1080p_video_on_cmd16, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd17), otm1901a_dj_1080p_video_on_cmd17, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd18), otm1901a_dj_1080p_video_on_cmd18, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd19), otm1901a_dj_1080p_video_on_cmd19, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd20), otm1901a_dj_1080p_video_on_cmd20, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd21), otm1901a_dj_1080p_video_on_cmd21, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd22), otm1901a_dj_1080p_video_on_cmd22, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd23), otm1901a_dj_1080p_video_on_cmd23, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd24), otm1901a_dj_1080p_video_on_cmd24, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd25), otm1901a_dj_1080p_video_on_cmd25, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd26), otm1901a_dj_1080p_video_on_cmd26, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd27), otm1901a_dj_1080p_video_on_cmd27, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd28), otm1901a_dj_1080p_video_on_cmd28, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd29), otm1901a_dj_1080p_video_on_cmd29, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd30), otm1901a_dj_1080p_video_on_cmd30, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd31), otm1901a_dj_1080p_video_on_cmd31, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd32), otm1901a_dj_1080p_video_on_cmd32, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd33), otm1901a_dj_1080p_video_on_cmd33, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd34), otm1901a_dj_1080p_video_on_cmd34, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd35), otm1901a_dj_1080p_video_on_cmd35, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd36), otm1901a_dj_1080p_video_on_cmd36, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd37), otm1901a_dj_1080p_video_on_cmd37, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd38), otm1901a_dj_1080p_video_on_cmd38, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd39), otm1901a_dj_1080p_video_on_cmd39, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd40), otm1901a_dj_1080p_video_on_cmd40, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd41), otm1901a_dj_1080p_video_on_cmd41, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd42), otm1901a_dj_1080p_video_on_cmd42, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd43), otm1901a_dj_1080p_video_on_cmd43, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd44), otm1901a_dj_1080p_video_on_cmd44, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd45), otm1901a_dj_1080p_video_on_cmd45, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd46), otm1901a_dj_1080p_video_on_cmd46, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd47), otm1901a_dj_1080p_video_on_cmd47, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd48), otm1901a_dj_1080p_video_on_cmd48, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd49), otm1901a_dj_1080p_video_on_cmd49, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd50), otm1901a_dj_1080p_video_on_cmd50, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd51), otm1901a_dj_1080p_video_on_cmd51, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd52), otm1901a_dj_1080p_video_on_cmd52, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd53), otm1901a_dj_1080p_video_on_cmd53, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd54), otm1901a_dj_1080p_video_on_cmd54, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd55), otm1901a_dj_1080p_video_on_cmd55, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd56), otm1901a_dj_1080p_video_on_cmd56, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd57), otm1901a_dj_1080p_video_on_cmd57, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd58), otm1901a_dj_1080p_video_on_cmd58, 0},
	/*remove VCOM
	{sizeof(otm1901a_dj_1080p_video_on_cmd59), otm1901a_dj_1080p_video_on_cmd59, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd60), otm1901a_dj_1080p_video_on_cmd60, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd61), otm1901a_dj_1080p_video_on_cmd61, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd62), otm1901a_dj_1080p_video_on_cmd62, 0},
	*/
	{sizeof(otm1901a_dj_1080p_video_on_cmd63), otm1901a_dj_1080p_video_on_cmd63, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd64), otm1901a_dj_1080p_video_on_cmd64, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd65), otm1901a_dj_1080p_video_on_cmd65, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd66), otm1901a_dj_1080p_video_on_cmd66, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd67), otm1901a_dj_1080p_video_on_cmd67, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd68), otm1901a_dj_1080p_video_on_cmd68, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd69), otm1901a_dj_1080p_video_on_cmd69, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd70), otm1901a_dj_1080p_video_on_cmd70, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd71), otm1901a_dj_1080p_video_on_cmd71, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd72), otm1901a_dj_1080p_video_on_cmd72, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd73), otm1901a_dj_1080p_video_on_cmd73, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd74), otm1901a_dj_1080p_video_on_cmd74, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd75), otm1901a_dj_1080p_video_on_cmd75, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd76), otm1901a_dj_1080p_video_on_cmd76, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd77), otm1901a_dj_1080p_video_on_cmd77, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd78), otm1901a_dj_1080p_video_on_cmd78, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd79), otm1901a_dj_1080p_video_on_cmd79, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd80), otm1901a_dj_1080p_video_on_cmd80, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd81), otm1901a_dj_1080p_video_on_cmd81, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd82), otm1901a_dj_1080p_video_on_cmd82, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd83), otm1901a_dj_1080p_video_on_cmd83, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd84), otm1901a_dj_1080p_video_on_cmd84, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd85), otm1901a_dj_1080p_video_on_cmd85, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd86), otm1901a_dj_1080p_video_on_cmd86, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd87), otm1901a_dj_1080p_video_on_cmd87, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd88), otm1901a_dj_1080p_video_on_cmd88, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd89), otm1901a_dj_1080p_video_on_cmd89, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd90), otm1901a_dj_1080p_video_on_cmd90, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd91), otm1901a_dj_1080p_video_on_cmd91, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd92), otm1901a_dj_1080p_video_on_cmd92, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd93), otm1901a_dj_1080p_video_on_cmd93, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd94), otm1901a_dj_1080p_video_on_cmd94, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd95), otm1901a_dj_1080p_video_on_cmd95, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd96), otm1901a_dj_1080p_video_on_cmd96, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd97), otm1901a_dj_1080p_video_on_cmd97, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd98), otm1901a_dj_1080p_video_on_cmd98, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd99), otm1901a_dj_1080p_video_on_cmd99, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd100), otm1901a_dj_1080p_video_on_cmd100, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd101), otm1901a_dj_1080p_video_on_cmd101, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd102), otm1901a_dj_1080p_video_on_cmd102, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd103), otm1901a_dj_1080p_video_on_cmd103, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd104), otm1901a_dj_1080p_video_on_cmd104, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd105), otm1901a_dj_1080p_video_on_cmd105, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd106), otm1901a_dj_1080p_video_on_cmd106, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd107), otm1901a_dj_1080p_video_on_cmd107, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd108), otm1901a_dj_1080p_video_on_cmd108, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd109), otm1901a_dj_1080p_video_on_cmd109, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd110), otm1901a_dj_1080p_video_on_cmd110, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd111), otm1901a_dj_1080p_video_on_cmd111, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd112), otm1901a_dj_1080p_video_on_cmd112, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd113), otm1901a_dj_1080p_video_on_cmd113, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd114), otm1901a_dj_1080p_video_on_cmd114, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd115), otm1901a_dj_1080p_video_on_cmd115, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd116), otm1901a_dj_1080p_video_on_cmd116, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd117), otm1901a_dj_1080p_video_on_cmd117, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd118), otm1901a_dj_1080p_video_on_cmd118, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd119), otm1901a_dj_1080p_video_on_cmd119, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd120), otm1901a_dj_1080p_video_on_cmd120, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd121), otm1901a_dj_1080p_video_on_cmd121, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd122), otm1901a_dj_1080p_video_on_cmd122, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd123), otm1901a_dj_1080p_video_on_cmd123, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd124), otm1901a_dj_1080p_video_on_cmd124, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd125), otm1901a_dj_1080p_video_on_cmd125, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd126), otm1901a_dj_1080p_video_on_cmd126, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd127), otm1901a_dj_1080p_video_on_cmd127, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd128), otm1901a_dj_1080p_video_on_cmd128, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd129), otm1901a_dj_1080p_video_on_cmd129, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd130), otm1901a_dj_1080p_video_on_cmd130, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd131), otm1901a_dj_1080p_video_on_cmd131, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd132), otm1901a_dj_1080p_video_on_cmd132, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd133), otm1901a_dj_1080p_video_on_cmd133, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd134), otm1901a_dj_1080p_video_on_cmd134, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd135), otm1901a_dj_1080p_video_on_cmd135, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd136), otm1901a_dj_1080p_video_on_cmd136, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd137), otm1901a_dj_1080p_video_on_cmd137, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd138), otm1901a_dj_1080p_video_on_cmd138, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd139), otm1901a_dj_1080p_video_on_cmd139, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd140), otm1901a_dj_1080p_video_on_cmd140, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd141), otm1901a_dj_1080p_video_on_cmd141, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd142), otm1901a_dj_1080p_video_on_cmd142, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd143), otm1901a_dj_1080p_video_on_cmd143, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd144), otm1901a_dj_1080p_video_on_cmd144, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd145), otm1901a_dj_1080p_video_on_cmd145, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd146), otm1901a_dj_1080p_video_on_cmd146, 0},
	{sizeof(otm1901a_dj_1080p_video_on_cmd147), otm1901a_dj_1080p_video_on_cmd147, 0x78},
	{sizeof(otm1901a_dj_1080p_video_on_cmd148), otm1901a_dj_1080p_video_on_cmd148, 0x14},
};

#define OTM1901A_DJ_1080P_VIDEO_ON_COMMAND 145

static char otm1901a_dj_1080p_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };

static char otm1901a_dj_1080p_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };

static struct mipi_dsi_cmd otm1901a_dj_1080p_video_off_command[] = {
{ 0x4 , otm1901a_dj_1080p_videooff_cmd0, 0x20},
{ 0x4 , otm1901a_dj_1080p_videooff_cmd1, 0x78}
};
#define OTM1901A_DJ_1080P_VIDEO_OFF_COMMAND 2


static struct command_state otm1901a_dj_1080p_video_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info otm1901a_dj_1080p_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info otm1901a_dj_1080p_video_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration otm1901a_dj_1080p_video_lane_config = {
  4, 0, 1, 1, 1, 1, 0
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t otm1901a_dj_1080p_video_timings[] = {
  0xDB, 0x34, 0x22, 0x00, 0x64, 0x66, 0x28, 0x38, 0x2B, 0x03, 0x04, 0x00
};

static const uint32_t otm1901a_dj_1080p_14nm_video_timings[] = {
	0x23, 0x1F, 0x07, 0x09, 0x05, 0x03, 0x04, 0xa0,
	0x23, 0x1F, 0x07, 0x09, 0x05, 0x03, 0x04, 0xa0,
	0x23, 0x1F, 0x07, 0x09, 0x05, 0x03, 0x04, 0xa0,
	0x23, 0x1F, 0x07, 0x09, 0x05, 0x03, 0x04, 0xa0,
	0x23, 0x1A, 0x07, 0x08, 0x05, 0x03, 0x04, 0xa0,
};


static struct panel_timing otm1901a_dj_1080p_video_timing_info = {
  0, 4, 0x3, 0x29
};

static struct panel_reset_sequence otm1901a_dj_1080p_video_panel_reset_seq = {
{ 1, 0, 1, }, { 50, 50, 50, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight otm1901a_dj_1080p_video_backlight = {
  1, 1, 4095, 100, 1, "PMIC_8941"
};

static struct labibb_desc otm1901a_dj_1080p_video_labibb = {
	0, 1, 5000000, 5000000, 5000000, 5000000, 3, 3, 1, 0
};

/* mindan@wingtech.com, 2016/03/18, set panel id register through panel_xxxxx.h file, begin */
//static char otm1901a_dj_1080p_panel_max_packet[4] = { 0x01, 0x00, 0x37, 0x80 };	/* DTYPE_SET_MAX_PACKET */

//static char otm1901a_dj_1080p_read_id_res_dah[4] = { 0xDA, 0x00, 0x06, 0xB0 };	/* DTYPE_SET_MAX_PACKET */

//static char otm1901a_dj_1080p_read_id_res_dbh[4] = { 0xDB, 0x00, 0x06, 0xB0 };	/* DTYPE_SET_MAX_PACKET */

//static struct mipi_dsi_cmd otm1901a_dj_1080p_panel_id_res[]={
//		{0x04,otm1901a_dj_1080p_panel_max_packet,0x00},
//		{0x04,otm1901a_dj_1080p_read_id_res_dah,0x00},
//		{0x04,otm1901a_dj_1080p_panel_max_packet,0x00},
//		{0x04, otm1901a_dj_1080p_read_id_res_dbh,0x00}
//	};

/* mindan@wingtech.com, 2016/03/18, set panel id register through panel_xxxxx.h file, end */


#define OTM1901A_DJ_1080P_VIDEO_SIGNATURE   0xB0B0//5596

#endif /*_PANEL_NT35596_1080P_VIDEO_H_*/
